stages:
  - build
  - release
  - deploy

variables:
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_DRIVER: 'overlay2'
  TEST_IMAGE: '$CI_REGISTRY_IMAGE:testing'
  RELEASE_IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG'
  PRODUCTION_IMAGE: '$CI_REGISTRY_IMAGE:latest'

.docker_job_template: &docker_job_definition
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - 'docker info'
    - 'docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY'
    - 'docker pull $TEST_IMAGE || true'

build:
  <<: *docker_job_definition
  stage: build
  script: |
    docker build \
      --target build \
      --cache-from $TEST_IMAGE \
      --tag $TEST_IMAGE \
      ./
    docker push $TEST_IMAGE

release:
  <<: *docker_job_definition
  stage: release
  only:
    - master
    - production
  script: |
    docker build \
      --target release \
      --tag $RELEASE_IMAGE \
      ./
    docker push $RELEASE_IMAGE

deploy:
  <<: *docker_job_definition
  stage: deploy
  only:
    - production
  script: |
    docker pull $RELEASE_IMAGE
    docker tag $RELEASE_IMAGE $PRODUCTION_IMAGE
    docker push $PRODUCTION_IMAGE
    wget --post-data="" $DEPLOY_WEBHOOK
