version: '3.4'
services:
  pixie:
    build:
      context: .
      target: development
      args:
        NODE_IMG_VER: $NODE_IMG_VER
        NODE_ENV: ${NODE_ENV:-development}
    image: pixie-dev
    container_name: pixie
    depends_on:
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${CLIENT_PORT:-3000}
      SERVER_PORT: ${SERVER_PORT:-8080}
      DEBUG_PORT: ${DEBUG_PORT:-9229}
      DB_URI: ${DB_URI}
      UNSPLASH_ID: ${UNSPLASH_ID}
    ports:
      - ${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
      - ${DEBUG_PORT:-9229}:${DEBUG_PORT:-9229}
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
      - yarn_cache:/home/node/.yarn-cache
  mongo:
    image: mongo
    container_name: pixie-mongo
    ports:
      - ${DB_PORT:-27017}:${DB_PORT:-27017}
    volumes:
      - mongo_config:/etc/mongo
      - mongo_configdb:/data/configdb
      - mongo_data:/data/db
volumes:
  yarn_cache:
  node_modules:
  mongo_config:
  mongo_configdb:
  mongo_data:
