version: '3.3'
services:
  pixie:
    image: registry.ajanzen.net/andrew/pixie:latest
    networks:
      - default
    secrets:
      - sendgrid_key
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      SERVER_PORT: ${SERVER_PORT}
      UNSPLASH_ID: ${UNSPLASH_ID:-/run/secrets/unsplash_key}
      DB_URI: ${DB_URI:-mongodb://mongo/pixie}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - assets:/srv/app/public
  pixie_proxy:
    image: nginx:alpine
    networks:
      - frontend
      - default
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    configs:
      - source: nginx_pixie
        target: /etc/nginx/conf.d/pixie.conf
    volumes:
      - assets:/var/www:ro
  mongo:
    image: mongo:latest
    networks:
      - default
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
configs:
  nginx_pixie:
    external: true
secrets:
  unsplash_key:
    external: true
networks:
  frontend:
    external: true
volumes:
  assets:
  data:
